using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement.MetaData;
using Orchard.Data.Migration;
using Onestop.Seo.Models;
using Orchard.Core.Contents.Extensions;

namespace Onestop.Seo {
    public class Migrations : DataMigrationImpl {
        public int Create() {
            SchemaBuilder.CreateTable(typeof(SeoGlobalSettingsPartRecord).Name,
                table => table
                    .ContentPartVersionRecord()
                    .Column<string>("HomeTitle", column => column.WithLength(1024))
                    .Column<string>("HomeDescription", column => column.Unlimited())
                    .Column<string>("HomeKeywords", column => column.Unlimited())
                    .Column<string>("ContentTitlePatternsDefinition", column => column.Unlimited())
                    .Column<bool>("EnableCanonicalUrls")
                    .Column<bool>("UseCategoriesForKeywords")
                    .Column<bool>("AutogenerateDescriptions")
                );

            SchemaBuilder.CreateTable(typeof(SeoOverridesPartRecord).Name,
                table => table
                    .ContentPartVersionRecord()
                    .Column<string>("TitleOverride", column => column.WithLength(1024))
                    .Column<string>("DescriptionOverride", column => column.Unlimited())
                );

            ContentDefinitionManager.AlterPartDefinition(typeof(SeoOverridesPart).Name, builder => builder.Attachable());


            return 1;
        }
    }
}