using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.Mvc.Filters;
using System.Web.Mvc;
using Onestop.Seo.Services;
using Orchard.Environment;
using Orchard.UI.Resources;
using Orchard.ContentManagement;
using Orchard.Core.Common.Models;
using Orchard.Utility.Extensions;

namespace Onestop.Seo.Filters {
    public class DescriptionFilter : FilterProvider, IResultFilter {
        private readonly Work<ISeoSettingsManager> _seoSettingsManagerWork;
        private readonly Work<ICurrentContentService> _currentContentServiceWork;
        private readonly Work<ISeoService> _seoServiceWork;
        private readonly Work<IResourceManager> _resourceManagerWork;

        public DescriptionFilter(
            Work<ISeoSettingsManager> seoSettingsManagerWork,
            Work<ICurrentContentService> currentContentServiceWork,
            Work<ISeoService> seoServiceWork,
            Work<IResourceManager> resourceManagerWork) {
            _seoSettingsManagerWork = seoSettingsManagerWork;
            _currentContentServiceWork = currentContentServiceWork;
            _seoServiceWork = seoServiceWork;
            _resourceManagerWork = resourceManagerWork;
        }

        public void OnResultExecuted(ResultExecutedContext filterContext) {
        }

        public void OnResultExecuting(ResultExecutingContext filterContext) {
            // Don't run on admin
            if (Orchard.UI.Admin.AdminFilter.IsApplied(filterContext.RequestContext)) return;

            // Don't run on home page
            if (filterContext.HttpContext.Request.Path == "/") return;

            var item = _currentContentServiceWork.Value.GetContentForRequest();
            if (item == null) return;

            // Rewritten descriptions should be handled here

            if (!_seoSettingsManagerWork.Value.GetGlobalSettings().AutogenerateDescriptions) return;

            var description = _seoServiceWork.Value.GenerateDescription(item);
            if (String.IsNullOrEmpty(description)) return;

            _resourceManagerWork.Value.SetMeta(new MetaEntry {
                Name = "description",
                Content = description
            });
        }
    }
}