using System;
using Orchard.ContentManagement;

namespace Onestop.Seo.Models {
    public interface ISeoGlobalSettings : IContent {
        string HomeTitle { get; }
        string HomeDescription { get; }
        string HomeKeywords { get; }
        void SetTitlePattern(string contentType, string pattern);
        string GetTitlePattern(string contentType);
        string SearchTitlePattern { get; }
        string ProductTitlePattern { get; }
        string ProductCategoryTitlePattern { get; }
        bool EnableCanonicalUrls { get; }
        bool UseCategoriesForKeywords { get; }
        bool AutogenerateDescriptions { get; }
    }
}
