using System;
using Orchard.ContentManagement;

namespace Onestop.Seo.Models {
    public interface ISeoGlobalSettings : IContent {
        string HomeTitle { get; set; }
        string HomeDescription { get; set; }
        string HomeKeywords { get; set; }
        string ContentCategoriesTitlePattern { get; set; }
        string ContentPagesTitlePattern { get; set; }
        bool EnableCanonicalUrls { get; set; }
        bool UseCategoriesForKeywords { get; set; }
        bool AutogenerateDescriptions { get; set; }
    }
}
