using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement.Records;
using System.ComponentModel.DataAnnotations;
using Orchard.ContentManagement;
using Orchard.Data.Conventions;

namespace Onestop.Seo.Models {
    public class SeoGlobalSettingsPart : ContentPart<SeoGlobalSettingsPartRecord> {
        [Required]
        public string HomeTitle {
            get { return Record.HomeTitle; }
            set { Record.HomeTitle = value; }
        }

        public string HomeDescription {
            get { return Record.HomeDescription; }
            set { Record.HomeDescription = value; }
        }

        public string HomeKeywords {
            get { return Record.HomeKeywords; }
            set { Record.HomeKeywords = value; }
        }

        public string ContentCategoriesTitlePattern {
            get { return Record.ContentCategoriesTitlePattern; }
            set { Record.ContentCategoriesTitlePattern = value; }
        }

        public string ContentPagesTitlePattern {
            get { return Record.ContentPagesTitlePattern; }
            set { Record.ContentPagesTitlePattern = value; }
        }

        public bool EnableCanonicalUrls {
            get { return Record.EnableCanonicalUrls; }
            set { Record.EnableCanonicalUrls = value; }
        }

        public bool UseCategoriesForKeywords {
            get { return Record.UseCategoriesForKeywords; }
            set { Record.UseCategoriesForKeywords = value; }
        }

        public bool AutogenerateDescriptions {
            get { return Record.AutogenerateDescriptions; }
            set { Record.AutogenerateDescriptions = value; }
        }
    }

    public class SeoGlobalSettingsPartRecord : ContentPartVersionRecord {
        [StringLength(1024)]
        public virtual string HomeTitle { get; set; }

        [StringLengthMax]
        public virtual string HomeDescription { get; set; }

        [StringLengthMax]
        public virtual string HomeKeywords { get; set; }

        [StringLength(1024)]
        public virtual string ContentCategoriesTitlePattern { get; set; }

        [StringLength(1024)]
        public virtual string ContentPagesTitlePattern { get; set; }

        public virtual bool EnableCanonicalUrls { get; set; }

        public virtual bool UseCategoriesForKeywords { get; set; }

        public virtual bool AutogenerateDescriptions { get; set; }
    }
}